Traceback (most recent call last):
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/bin/airflow", line 27, in <module>
    args.func(args)
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/lib/python2.7/site-packages/airflow/bin/cli.py", line 817, in scheduler
    with ctx:
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/lib/python2.7/site-packages/daemon/daemon.py", line 397, in __enter__
    self.open()
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/lib/python2.7/site-packages/daemon/daemon.py", line 389, in open
    self.pidfile.__enter__()
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/lib/python2.7/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/lib/python2.7/site-packages/daemon/pidfile.py", line 60, in acquire
    super(TimeoutPIDLockFile, self).acquire(timeout, *args, **kwargs)
  File "/Users/ishanarora/PycharmProjects/RedshiftSampleETL/env/lib/python2.7/site-packages/lockfile/pidlockfile.py", line 88, in acquire
    self.path)
lockfile.AlreadyLocked: /Users/ishanarora/PycharmProjects/RedshiftSampleETL/airflow_home/airflow-scheduler.pid is already locked
